server:
  port: ${PORT:8080}
  max-http-header-size: 16384

spring:
  main:
    banner-mode: "off"
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true

logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      tingcore:
        organization: INFO
    root: INFO

info:
  app:
    name: ${spring.application.name}
    version: ${VERSION:unknown}

app:
  allowed-origins: https://localhost:3000
  payments-service:
    base-url: https://${integration.payments.hostname}
    default-timeout: 20 # timeout in seconds
  user-service:
    base-url: https://${integration.user.hostname}
    default-timeout: 20 # timeout in seconds
  asset-service:
    base-url: https://${integration.asset.hostname}
    default-timeout: 20
  charging-operations-service:
    base-url: https://${integration.charging-operations.hostname}
    default-timeout: 20
  customer-key-order-service:
    base-url: https://${integration.customer-key-order.hostname}
    default-timeout: 20
  campaign-service:
    base-url: https://${integration.campaign.hostname}
    default-timeout: 10

integration:
  payments:
    hostname: payments-service.tingcore-test.com
  user:
    hostname: user-service.tingcore-test.com
  asset:
    hostname: asset-service.tingcore-test.com
  charging-operations:
    hostname: charging-operations.tingcore-test.com
  customer-key-order:
    hostname: customer-key-order.tingcore-test.com
  campaign:
    hostname: campaign-service.tingcore-test.com

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, prometheus
      path-mapping:
        prometheus: /metrics

tracing:
  xray:
    enabled: false
