integration:
  payments:
    hostname: payments-service.tingcore-stage.com
  user:
    hostname: user-service-stage.tingcore-infra.com
  asset:
    hostname: asset-service-stage.tingcore-infra.com
  charging-operations:
    hostname: charging-operations.tingcore-stage.com
