server:
  port: 8082

spring:
  profiles:
    active: dev
    include: payments-receipt-v2
logging:
  level:
    org:
      springframework: INFO
    com:
      tingcore:
        organizstion: DEBUG
    root: INFO

app:
  user-service:
    base-url: https://${integration.user.hostname}

integration:
  payments:
    hostname: payments-service.tingcore-test.com
