app:
  allowed-origins: "*"

integration:
  payments:
    hostname: payments-service.tingcore-stage.com
  user:
    hostname: user-service.tingcore-stage.com
  asset:
    hostname: asset-service.tingcore-stage.com
  charging-operations:
    hostname: charging-operations.tingcore-stage.com
  customer-key-order:
    hostname: customer-key-order.tingcore-stage.com
