server:
  port: 8082

spring:
  profiles:
    include: session-history-v2,charging-sessions-v2,payments-receipt-v2,advanced-pricing

logging:
  level:
    org.springframework: INFO
    root: WARN

integration:
  payments:
    hostname: payments-service.tingcore-test.com
  user:
    hostname: user-service.tingcore-test.com
  asset:
    hostname: asset-service.tingcore-test.com
  charging-operations:
    hostname: charging-operations.tingcore-test.com
  customer-key-order:
    hostname: customer-key-order.tingcore-test.com
  campaign:
    hostname: campaign-service.tingcore-test.com
  history:
    hostname: session-history.tingcore-test.com
  receipt:
    hostname: payments-receipt.tingcore-test.com
  sessions:
    hostname: payments-sessions.tingcore-test.com
  partnerships:
    hostname: partnerships-service.tingcore-test.com
  pricing:
    hostname: payments-pricing.tingcore-test.com
