server:
  port: ${PORT:8080}
  max-http-header-size: 16384

spring:
  main:
    banner-mode: "off"
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true

logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      tingcore:
        organization: INFO
    root: INFO

info:
  app:
    name: ${spring.application.name}
    version: ${VERSION:unknown}

app:
  allowed-origins: http://localhost:3000
  payments-service:
    base-url: http://${integration.payments.hostname}
    default-timeout: 20 # timeout in seconds
  user-service:
    base-url: https://${integration.user.hostname}
    default-timeout: 20 # timeout in seconds
  asset-service:
    base-url: http://${integration.asset.hostname}
    default-timeout: 20
  charging-operations-service:
    base-url: http://${integration.charging-operations.hostname}
    default-timeout: 20

integration:
  payments:
    hostname: payments-service.tingcore-test.com
  user:
    hostname: user-service.tingcore-test.com
  asset:
    hostname: asset-service.tingcore-test.com
  charging-operations:
    hostname: charging-operations.tingcore-test.com