integration:
  payments:
    hostname: payments-service.tingcore-test.com
  user:
    hostname: user-service-test.tingcore-infra.com
  asset:
    hostname: asset-service.tingcore-test.com
  charging-operations:
    hostname: charging-operations.tingcore-test.com

app:
  allowed-origins: http://localhost:3000
  payments-service:
    base-url: https://${integration.payments.hostname}
    default-timeout: 20
  user-service:
    base-url: https://${integration.user.hostname}
    default-timeout: 20
  asset-service:
    base-url: https://${integration.asset.hostname}
    default-timeout: 20
  charging-operations-service:
    base-url: https://${integration.charging-operations.hostname}
    default-timeout: 20
