integration:
  payments:
    hostname: payments-service.tingcore-test.com
  user:
    hostname: user-service.tingcore-test.com
  asset:
    hostname: asset-service.tingcore-test.com
  charging-operations:
    hostname: charging-operations.tingcore-test.com