server:
  port: 8082

spring:
  profiles:
    active: dev
logging:
  level:
    org:
      springframework: INFO
    com:
      tingcore:
        organizstion: DEBUG
    root: INFO

app:
  user-service:
    #base-url: http://${integration.user.hostname}
    base-url: https://user-service-test.tingcore-infra.com

integration:
  payments:
    hostname: payments-service.tingcore-test.com