server:
  port: ${PORT:8080}
  max-http-header-size: 16384

spring:
  main:
    banner-mode: "off"
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true

logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      tingcore:
        organization: INFO
    root: INFO

info:
  app:
    name: ${spring.application.name}
    version: ${VERSION:unknown}

app:
  user-service:
    base-url: http://localhost:8085
security:
  header: X-Authorization-Id

integration:
  user:
    hostname: user-service-test.tingcore-infra.com
  asset:
    hostname: asset-service-test.tingcore-infra.com
