server:
  port: 8082

spring:
  profiles:
    active: dev
logging:
  level:
    org:
      springframework: INFO
    com:
      tingcore:
        organizstion: DEBUG
    root: INFO

security:
  basic:
    enabled: false

app:
  user-service:
    base-url: http://localhost:8085